# Generated by Django 4.2.7 on 2024-01-15 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_name", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("name_from_user", models.CharField(max_length=100, null=True)),
                ("telephone_number", models.CharField(max_length=100, null=True)),
                (
                    "urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("request", models.BooleanField(default=False)),
            ],
        ),
    ]
